name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Validate TypeScript types
        run: bun run check

      - name: Install Chromium
        run: bunx playwright install chromium

      - name: Validate Chromium behavior
        run: bun run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # CODECOV_TOKEN is configured as a repository secret
          token: ${{ secrets.CODECOV_TOKEN }}
